// js/data.js
// Colores, tipos y productos. Edita este archivo para agregar o modificar gorras.
window.DATA = {

  colores: [
    { id: 'rojo',        nombre: 'Rojo',       hex: '#D7263D' },
    { id: 'azul-marino', nombre: 'Azul marino', hex: '#1B2A4A' },
    { id: 'mostaza',     nombre: 'Mostaza',     hex: '#E0A526' },
    { id: 'verde-oliva', nombre: 'Verde oliva', hex: '#4B5D3A' },
    { id: 'rosa-palo',   nombre: 'Rosa palo',   hex: '#F2A7B8' },
    { id: 'arena',       nombre: 'Arena',       hex: '#CBB68B' },
    { id: 'hueso',       nombre: 'Hueso',       hex: '#EDE8DC' },
    { id: 'negro',       nombre: 'Negro',       hex: '#1A1A1A' }
  ],

  tipos: [
    { id: 'snapback',   nombre: 'Snapback',   ilustracion: 'snapback' },
    { id: 'trucker',    nombre: 'Trucker',    ilustracion: 'trucker'  },
    { id: 'dad',        nombre: 'Dad hat',    ilustracion: 'dad'      },
    { id: 'beisbolera', nombre: 'Beisbolera', ilustracion: 'fitted'   },
    { id: 'bucket',     nombre: 'Bucket',     ilustracion: 'bucket'   }
  ],

  productos: [
    {
      id: 'clasica-snap',
      nombre: 'Clásica Snap',
      tipo: 'snapback',
      precio: 24.90,
      precioAntes: null,
      etiqueta: 'mas-vendida',
      destacada: true,
      disponible: true,
      fecha: '2026-08-20',
      colores: [
        { id: 'negro' },
        { id: 'hueso', secundario: 'negro' },
        { id: 'rojo', secundario: 'negro' },
        { id: 'azul-marino', secundario: 'hueso' }
      ],
      resumen: 'Visera plana, copa alta y el cierre de siempre.',
      descripcion: 'Copa alta y visera plana, como las de siempre. El cierre snapback se ajusta en segundos y la copa estructurada conserva su forma. Poliéster y algodón de peso medio para uso diario.',
      material: 'Poliéster y algodón',
      ajuste: 'Cierre snapback ajustable',
      visera: 'Plana',
      tallas: 'Única, de 54 a 60 cm',
      cuidado: 'Lavar a mano. No usar secadora.',
      tags: ['clásica', 'diaria', 'unisex', 'snapback', 'básica']
    },
    {
      id: 'plana-calle',
      nombre: 'Plana Calle',
      tipo: 'snapback',
      precio: 26.90,
      precioAntes: null,
      etiqueta: 'nuevo',
      destacada: true,
      disponible: true,
      fecha: '2026-09-15',
      colores: [
        { id: 'negro' },
        { id: 'arena', secundario: 'verde-oliva' },
        { id: 'verde-oliva' }
      ],
      resumen: 'Visera ultraplana con parche bordado en el frente.',
      descripcion: 'Visera ultraplana que no se tuerce. El parche frontal bordado da un acabado limpio. Cierre snapback de plástico con cinco posiciones de ajuste para un calce exacto.',
      material: 'Poliéster y algodón',
      ajuste: 'Cierre snapback ajustable',
      visera: 'Plana',
      tallas: 'Única, de 54 a 60 cm',
      cuidado: 'Lavar a mano. No usar secadora.',
      tags: ['urbana', 'calle', 'snapback', 'plana', 'bordado']
    },
    {
      id: 'bloque',
      nombre: 'Bloque',
      tipo: 'snapback',
      precio: 22.90,
      precioAntes: null,
      etiqueta: null,
      destacada: false,
      disponible: true,
      fecha: '2026-07-10',
      colores: [
        { id: 'rojo' },
        { id: 'negro', secundario: 'mostaza' },
        { id: 'mostaza', secundario: 'negro' }
      ],
      resumen: 'Dos colores en bloques bien definidos, copa alta.',
      descripcion: 'Copa alta en dos bloques de color con costuras visibles entre paneles. El contraste es directo y sin adornos. Cierre snapback estándar y visera plana sin curvatura.',
      material: 'Poliéster y algodón',
      ajuste: 'Cierre snapback ajustable',
      visera: 'Plana',
      tallas: 'Única, de 54 a 60 cm',
      cuidado: 'Lavar a mano. No usar secadora.',
      tags: ['bicolor', 'bloques', 'snapback', 'contraste', 'atrevida']
    },
    {
      id: 'malla-ruta',
      nombre: 'Malla Ruta',
      tipo: 'trucker',
      precio: 21.90,
      precioAntes: null,
      etiqueta: null,
      destacada: false,
      disponible: true,
      fecha: '2026-07-22',
      colores: [
        { id: 'hueso', secundario: 'negro' },
        { id: 'negro' },
        { id: 'azul-marino', secundario: 'hueso' }
      ],
      resumen: 'Panel de espuma al frente y malla transpirable atrás.',
      descripcion: 'Panel frontal de espuma estructurada y malla trasera que deja correr el aire. Diseño sin estampados para combinar con cualquier atuendo. Visera ligeramente curva y altura media.',
      material: 'Frente de espuma y malla transpirable',
      ajuste: 'Cierre snapback ajustable',
      visera: 'Ligeramente curva',
      tallas: 'Única, de 54 a 60 cm',
      cuidado: 'Limpiar con paño húmedo.',
      tags: ['trucker', 'malla', 'transpirable', 'básica', 'diaria']
    },
    {
      id: 'camionero',
      nombre: 'Camionero',
      tipo: 'trucker',
      precio: 23.90,
      precioAntes: null,
      etiqueta: null,
      destacada: true,
      disponible: true,
      fecha: '2026-08-05',
      colores: [
        { id: 'verde-oliva', secundario: 'hueso' },
        { id: 'arena', secundario: 'hueso' },
        { id: 'rojo', secundario: 'hueso' }
      ],
      resumen: 'Frente espumado, malla hueso y logo cosido al frente.',
      descripcion: 'Combinación clásica de frente espumado y malla color hueso. El logo cosido al panel frontal tiene un relieve sutil. Cierre snapback de cinco posiciones y visera con curva suave.',
      material: 'Frente de espuma y malla transpirable',
      ajuste: 'Cierre snapback ajustable',
      visera: 'Ligeramente curva',
      tallas: 'Única, de 54 a 60 cm',
      cuidado: 'Limpiar con paño húmedo.',
      tags: ['trucker', 'malla', 'camionero', 'retro', 'ventilada']
    },
    {
      id: 'malla-desierto',
      nombre: 'Malla Desierto',
      tipo: 'trucker',
      precio: 23.90,
      precioAntes: null,
      etiqueta: null,
      destacada: false,
      disponible: false,
      fecha: '2026-07-30',
      colores: [
        { id: 'arena', secundario: 'negro' },
        { id: 'hueso', secundario: 'arena' },
        { id: 'mostaza', secundario: 'negro' }
      ],
      resumen: 'Tonos tierra con malla oscura y copa media.',
      descripcion: 'Paleta de tonos tierra combinada con malla oscura en la parte trasera. Copa de altura media con seis paneles. Ideal para días al sol; la malla ventila sin perder estructura.',
      material: 'Frente de espuma y malla transpirable',
      ajuste: 'Cierre snapback ajustable',
      visera: 'Ligeramente curva',
      tallas: 'Única, de 54 a 60 cm',
      cuidado: 'Limpiar con paño húmedo.',
      tags: ['trucker', 'tierra', 'desierto', 'verano', 'malla']
    },
    {
      id: 'papa-suave',
      nombre: 'Papá Suave',
      tipo: 'dad',
      precio: 19.90,
      precioAntes: null,
      etiqueta: null,
      destacada: true,
      disponible: true,
      fecha: '2026-08-12',
      colores: [
        { id: 'hueso' },
        { id: 'rosa-palo' },
        { id: 'azul-marino' },
        { id: 'arena' }
      ],
      resumen: 'Algodón lavado, copa baja y ajuste con hebilla.',
      descripcion: 'Algodón lavado que se siente suave desde el primer uso. Copa baja y visera curva que se puede moldear a gusto. La hebilla metálica ajusta al centímetro y no pica.',
      material: 'Algodón lavado',
      ajuste: 'Correa con hebilla metálica',
      visera: 'Curva',
      tallas: 'Única, de 54 a 60 cm',
      cuidado: 'Lavar a mano.',
      tags: ['dad', 'suave', 'casual', 'algodón', 'ajustable']
    },
    {
      id: 'papa-vintage',
      nombre: 'Papá Vintage',
      tipo: 'dad',
      precio: 21.90,
      precioAntes: null,
      etiqueta: null,
      destacada: false,
      disponible: true,
      fecha: '2026-07-18',
      colores: [
        { id: 'verde-oliva' },
        { id: 'mostaza' },
        { id: 'arena' }
      ],
      resumen: 'Estética desgastada con lavado especial y copa baja.',
      descripcion: 'Lavado especial que imita el desgaste natural del tiempo. Los colores vienen atenuados para un look más orgánico. Copa baja y flexible que cae con naturalidad.',
      material: 'Algodón lavado',
      ajuste: 'Correa con hebilla metálica',
      visera: 'Curva',
      tallas: 'Única, de 54 a 60 cm',
      cuidado: 'Lavar a mano.',
      tags: ['dad', 'vintage', 'retro', 'desgastado', 'orgánico']
    },
    {
      id: 'papa-lavada',
      nombre: 'Papá Lavada',
      tipo: 'dad',
      precio: 17.90,
      precioAntes: 22.40,
      etiqueta: 'oferta',
      destacada: false,
      disponible: true,
      fecha: '2026-07-05',
      colores: [
        { id: 'azul-marino' },
        { id: 'negro' },
        { id: 'rojo' }
      ],
      resumen: 'Oferta en dad hat de colores sólidos, fácil de lavar.',
      descripcion: 'Dad hat de color sólido en algodón ligero que se lava a mano sin perder la forma. Copa baja con visera que acepta curva a gusto. Colores oscuros que no destiñen con el uso.',
      material: 'Algodón lavado',
      ajuste: 'Correa con hebilla metálica',
      visera: 'Curva',
      tallas: 'Única, de 54 a 60 cm',
      cuidado: 'Lavar a mano.',
      tags: ['dad', 'oferta', 'sólido', 'lavable', 'algodón']
    },
    {
      id: 'liga-pro',
      nombre: 'Liga Pro',
      tipo: 'beisbolera',
      precio: 29.90,
      precioAntes: null,
      etiqueta: 'mas-vendida',
      destacada: true,
      disponible: true,
      fecha: '2026-08-25',
      colores: [
        { id: 'negro' },
        { id: 'azul-marino' },
        { id: 'rojo' }
      ],
      resumen: 'Beisbolera estructurada, cerrada y con parche lateral.',
      descripcion: 'Copa estructurada en poliéster que mantiene la forma incluso con uso intenso. Visera curva precurvada en fábrica. Cierre trasero cerrado con costura central y parche rectangular a un lado.',
      material: 'Poliéster estructurado',
      ajuste: 'Cerrada, por tallas',
      visera: 'Curva',
      tallas: 'S/M y L/XL',
      cuidado: 'Limpiar con paño húmedo.',
      tags: ['beisbolera', 'estructurada', 'fitted', 'clásica', 'deporte']
    },
    {
      id: 'liga-clasica',
      nombre: 'Liga Clásica',
      tipo: 'beisbolera',
      precio: 27.90,
      precioAntes: null,
      etiqueta: null,
      destacada: false,
      disponible: true,
      fecha: '2026-08-08',
      colores: [
        { id: 'hueso' },
        { id: 'negro' },
        { id: 'azul-marino' }
      ],
      resumen: 'Beisbolera en colores neutros, copa redondeada.',
      descripcion: 'Colores neutros para un look sin esfuerzo. Copa redondeada en seis paneles con botón superior a la vista. El parche frontal lleva el logo bordado en hilo del mismo color.',
      material: 'Poliéster estructurado',
      ajuste: 'Cerrada, por tallas',
      visera: 'Curva',
      tallas: 'S/M y L/XL',
      cuidado: 'Limpiar con paño húmedo.',
      tags: ['beisbolera', 'neutro', 'clásica', 'bordado', 'tono']
    },
    {
      id: 'liga-sport',
      nombre: 'Liga Sport',
      tipo: 'beisbolera',
      precio: 31.90,
      precioAntes: null,
      etiqueta: 'nuevo',
      destacada: true,
      disponible: true,
      fecha: '2026-09-20',
      colores: [
        { id: 'azul-marino', secundario: 'rojo' },
        { id: 'negro', secundario: 'mostaza' },
        { id: 'rojo', secundario: 'hueso' }
      ],
      resumen: 'Dos colores, visera curva y acabado deportivo.',
      descripcion: 'Combinación de dos colores con visera y copa contrastantes. Poliéster de alta densidad que resiste la sudoración. Talla cerrada que da un calce firme y centrado.',
      material: 'Poliéster estructurado',
      ajuste: 'Cerrada, por tallas',
      visera: 'Curva',
      tallas: 'S/M y L/XL',
      cuidado: 'Limpiar con paño húmedo.',
      tags: ['beisbolera', 'sport', 'bicolor', 'deporte', 'fitted']
    },
    {
      id: 'bucket-dia',
      nombre: 'Bucket Día',
      tipo: 'bucket',
      precio: 25.90,
      precioAntes: null,
      etiqueta: null,
      destacada: true,
      disponible: true,
      fecha: '2026-09-02',
      colores: [
        { id: 'arena' },
        { id: 'hueso' },
        { id: 'verde-oliva' }
      ],
      resumen: 'Algodón twill, ala completa y filas de puntadas visibles.',
      descripcion: 'Algodón twill de punto cerrado con ala en todo el contorno para proteger del sol. Dos filas de puntadas decorativas marcan el ala. Se dobla sin deformarse y cabe en cualquier bolsillo.',
      material: 'Algodón twill',
      ajuste: 'Sin ajuste',
      visera: 'Ala completa',
      tallas: 'S/M y L/XL',
      cuidado: 'Lavable a máquina en agua fría.',
      tags: ['bucket', 'sol', 'twill', 'plegable', 'día']
    },
    {
      id: 'bucket-noche',
      nombre: 'Bucket Noche',
      tipo: 'bucket',
      precio: 20.90,
      precioAntes: 26.10,
      etiqueta: 'oferta',
      destacada: false,
      disponible: true,
      fecha: '2026-07-28',
      colores: [
        { id: 'negro' },
        { id: 'rosa-palo' },
        { id: 'mostaza' }
      ],
      resumen: 'Algodón twill con ala completa en colores nocturnos.',
      descripcion: 'Algodón twill con ala completa que da sombra a la cara y al cuello. Se dobla y cabe en el bolsillo de una chaqueta. Colores pensados para la tarde y la noche urbana.',
      material: 'Algodón twill',
      ajuste: 'Sin ajuste',
      visera: 'Ala completa',
      tallas: 'S/M y L/XL',
      cuidado: 'Lavable a máquina en agua fría.',
      tags: ['bucket', 'noche', 'urbana', 'twill', 'plegable']
    }
  ]

};
